server:
  port: 233
  servlet:
    context-path: /
spring:
  profiles:
    #数据源
    active: jdbc-company
  mvc:
    #设置静态资源路径
    static-path-pattern: /static/**
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        #懒加载配置
        enable_lazy_load_no_trans: true
  jackson:
    #为null时不返回
    default-property-inclusion: non_null
  datasource:
    druid:
      #初始化链接数
      initial-size: 5
      #最大连接
      max-active: 20
      #最小空闲
      min-idle: 10
      #最大超时ms
      max-wait: 3000
      #检测关闭空闲连接的时间ms
      time-between-eviction-runs-millis: 60000
      #filter
      filters: stat,wall
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
shiro:
  login_url: /login
  success_url: /index
  unauthorized_url: /403
  #加密方式
  algorithm_name: MD5
  #迭代次数
  iteration: 1024
  #false使用base64编码
  hex_encoded: false
  #最大密码错误数
  retry_max: 5
debug: false