-- MySQL Script generated by MySQL Workbench
-- Fri Mar 30 00:56:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mcblog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mcblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mcblog` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `mcblog` ;

-- -----------------------------------------------------
-- Table `mcblog`.`app_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcblog`.`app_user` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户表主键',
  `username` VARCHAR(45) NOT NULL COMMENT '用户名',
  `password` VARCHAR(32) NOT NULL,
  `salt` VARCHAR(32) NOT NULL COMMENT '密码加盐',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '0未激活 1正常 3冻结',
  `phone` VARCHAR(11) NULL,
  `email` VARCHAR(32) NULL,
  `ip_address` VARCHAR(15) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcblog`.`app_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcblog`.`app_role` (
  `role_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '角色表主键',
  `role_key` VARCHAR(20) NOT NULL,
  `role_name` VARCHAR(50) NOT NULL COMMENT '角色名称',
  `super_id` BIGINT NOT NULL DEFAULT -1 COMMENT '父级角色',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_id_UNIQUE` (`role_id` ASC),
  UNIQUE INDEX `role_key_UNIQUE` (`role_key` ASC))
ENGINE = InnoDB
COMMENT = '角色表';


-- -----------------------------------------------------
-- Table `mcblog`.`app_fn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcblog`.`app_fn` (
  `fn_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '权限表主键',
  `fn_name` VARCHAR(45) NOT NULL COMMENT '权限名称',
  `fn_key` VARCHAR(20) NOT NULL,
  `fn_url` VARCHAR(512) NOT NULL COMMENT '权限控制url',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '权限状态1启动 0停用',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`fn_id`),
  UNIQUE INDEX `fn_id_UNIQUE` (`fn_id` ASC),
  UNIQUE INDEX `fn_key_UNIQUE` (`fn_key` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcblog`.`app_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcblog`.`app_user_role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  `remark` VARCHAR(256) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `role_id_idx` (`role_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `user_role_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `mcblog`.`app_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_user_id_fk`
    FOREIGN KEY (`role_id`)
    REFERENCES `mcblog`.`app_role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcblog`.`app_role_fn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcblog`.`app_role_fn` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT NOT NULL,
  `fn_id` BIGINT NOT NULL,
  `remark` VARCHAR(256) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `role_id_idx` (`role_id` ASC),
  INDEX `fn_id_idx` (`fn_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `role_fn_id_fk`
    FOREIGN KEY (`role_id`)
    REFERENCES `mcblog`.`app_role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fn_role_id_fk`
    FOREIGN KEY (`fn_id`)
    REFERENCES `mcblog`.`app_fn` (`fn_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '权限表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
